Build ANE and test apps using the following SDKs: Android: - MoPub v3.2.2 - MMedia v5.3.0 - GPS v6.1.71 - Vungle v3.1.1
iOS:
- MoPub v3.2.0
- MMedia v5.3.0
- AdMob v6.12.2
- Vungle v3.0.11

Build tools:
- Flex 4.13.0
- AIR 15.0.0.356*
- Android API Level 19
- JDK 1.6
- Ant 1.9.4

* Note that the new Google Play Services ads SDK has some classes which were being stripped out when building using JDK 1.6. Therefore dx.jar in the AIR SDK was replaced by the version in Android build tools 21.1.1. Reference: http://stackoverflow.com/questions/24777394/noclassdeffounderror-on-thirdparty-class-files-when-building-adobe-native-extens